apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app-container
        image: python-app-image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: NAME
          value: "Suyog"
        - name: TESTENV
          value: "testenv"
---
apiVersion: v1
kind: Service
metadata:
  name: python-app-service
spec:
  type: ClusterIP
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
