name: demo-workflow
on: workflow_dispatch

jobs:
  demo-jobs:
    runs-on: ubuntu-latest
    steps: 
      - name: print hello world
        run: |
          echo "Hello world"
          pwd
      - name: checkout action
        uses: actions/checkout@v4

