name: simple-python-app-github-actions
on: 
  workflow_dispatch:
  push:
    branches:
      - github-actions-python-app  # triggers only when code is pushed to the 'github-actions-python-app' branch
# Set minimum required permissions for the workflow
permissions:
  contents: read      # needed to checkout code

jobs:
  python-app-build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.13]
    env:
      APP_DIR: CI-CD/GitHub-Actions/simple-python-app
    steps:
      - name: code checkout from github-actions-python-app branch
        uses: actions/checkout@v4
        # with:
        #   ref: github-actions-python-app
      - name: setup python 
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: list content
        run: |
          echo "Current directory: $PWD"
          echo "Files in simple-python-app" && ls $APP_DIR
      - name: install requirements 
        run: |
          FILE=$APP_DIR/requirements.txt
          if [ -f "$FILE" ]; then
            pip install -r "$FILE"
          else
            echo "$FILE not found, skipping install"
          fi
      - name: run app 
        env: 
          NAME: Suyog  #variable input to app.py file
          TESTENV: testenv
        run: |
          python $APP_DIR/app.py
      - name: test app
        #working-directory: CI-CD/GitHub-Actions/simple-python-app
        run: |
          cd $APP_DIR
          python -m unittest discover 
